# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: development
  pool: 5
  username: Domas
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: test
  pool: 5
  username: Domas
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: test
  pool: 5
  username: Domas
  password:
